package TVision;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.GraphicsEnvironment;
import java.awt.List;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ZxoR (Yonatan)
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() throws IOException {
        initComponents();
        DefaultTableCellRenderer rightRenderer_c = new DefaultTableCellRenderer();
        DefaultTableCellRenderer rightRenderer_h = new DefaultTableCellRenderer();
        rightRenderer_c.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        ArrayList<JTable> Tables = new ArrayList();
        Tables.add(channelsTable);
        Tables.add(showsTable);
        for (JTable t : Tables) {
            rightRenderer_h = (DefaultTableCellRenderer) t.getTableHeader().getDefaultRenderer();
            rightRenderer_h.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
            for (int i = 0; i < t.getColumnCount(); i++) {
                t.getColumnModel().getColumn(i).setCellRenderer(rightRenderer_c);
            }
        }
        isramedia.loadChannelsListToTable((DefaultTableModel) channelsTable.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        channelsTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        showsTable = new javax.swing.JTable();
        headText = new javax.swing.JLabel();
        pBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TVision version 0.5");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(20, 404));

        channelsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "שם הערוץ", "#"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        channelsTable.getTableHeader().setReorderingAllowed(false);
        channelsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channelsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(channelsTable);
        channelsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (channelsTable.getColumnModel().getColumnCount() > 0) {
            channelsTable.getColumnModel().getColumn(1).setMinWidth(35);
            channelsTable.getColumnModel().getColumn(1).setPreferredWidth(55);
            channelsTable.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        showsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ז'אנר", "אורך", "תוכנית", "שעה"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(showsTable);
        if (showsTable.getColumnModel().getColumnCount() > 0) {
            showsTable.getColumnModel().getColumn(2).setMinWidth(200);
            showsTable.getColumnModel().getColumn(2).setPreferredWidth(400);
            showsTable.getColumnModel().getColumn(2).setMaxWidth(500);
            showsTable.getColumnModel().getColumn(3).setMinWidth(60);
            showsTable.getColumnModel().getColumn(3).setPreferredWidth(60);
            showsTable.getColumnModel().getColumn(3).setMaxWidth(85);
        }

        headText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        headText.setText("לוח שידורים");

        pBar.setMaximum(6);
        pBar.setToolTipText("");
        pBar.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 589, Short.MAX_VALUE)
                        .addComponent(headText))
                    .addComponent(pBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(headText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void channelsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channelsTableMouseClicked
        if (evt.getClickCount() == 2) {
                        pBar.enable(true);
            pBar.setValue(1);
            GraphicsEnvironment.getLocalGraphicsEnvironment().registerFont(headText.getFont());
            DefaultTableModel model = (DefaultTableModel) channelsTable.getModel();
            final String channel = (String) channelsTable.getValueAt(channelsTable.getSelectedRow(), 1);
            final String head = (String) channelsTable.getValueAt(channelsTable.getSelectedRow(), 0);
            final DefaultTableModel modelshow = (DefaultTableModel) showsTable.getModel();
            modelshow.setRowCount(0);
            pBar.setValue(2);
            Thread t = new Thread(new Runnable() {
                public void run() {
                    try {
                        pBar.setValue(3);
                        isramedia.getListToTableModel(channel + "/%D7%A2%D7%A8%D7%95%D7%A5-1-%D7%A9%D7%99%D7%93%D7%95%D7%A8-%D7%97%D7%99", modelshow, pBar);
                    } catch (IOException ex) {
                        Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    finally {
                                    headText.setText(head);
            pBar.setValue(0);
            pBar.enable(false);   
                    }
                }
            });
            t.start();
        }
    }//GEN-LAST:event_channelsTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new main().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable channelsTable;
    private javax.swing.JLabel headText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JProgressBar pBar;
    private javax.swing.JTable showsTable;
    // End of variables declaration//GEN-END:variables

}
